// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnfT23ELDVI70Yc9-C7aCDfjlzdFt55is',
    appId: '1:388100637956:android:9719885f75bbbfc950bc51',
    messagingSenderId: '388100637956',
    projectId: 'ns-support-hub-2fd4d',
    storageBucket: 'ns-support-hub-2fd4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL7n_kqKgrkW_6da2OiZ6phWRcSzDsXOs',
    appId: '1:388100637956:ios:56409165582f4ccd50bc51',
    messagingSenderId: '388100637956',
    projectId: 'ns-support-hub-2fd4d',
    storageBucket: 'ns-support-hub-2fd4d.firebasestorage.app',
    iosBundleId: 'com.example.nsCommunitySupportHub',
  );


  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCX-GfjFTkVMDJygvWUVenX2MtnKFYLUmw",
      authDomain: "ns-support-hub-2fd4d.firebaseapp.com",
      projectId: "ns-support-hub-2fd4d",
      storageBucket: "ns-support-hub-2fd4d.firebasestorage.app",
      messagingSenderId: "388100637956",
      appId: "1:388100637956:web:612f0e718289241f50bc51",
      measurementId: "G-HJMBCTJHX2"
  );



}